export interface ThemeColors {
  background: string;
  surface: string;
  surfaceSecondary: string;
  surfaceElevated: string;
  card: string;
  text: string;
  textSecondary: string;
  textTertiary: string;
  border: string;
  borderLight: string;
  primary: string;
  primaryDark: string;
  primaryLight: string;
  accent: string;
  error: string;
  errorLight: string;
  success: string;
  successLight: string;
  warning: string;
  warningLight: string;
  pending: string;
  pendingBg: string;
  accepted: string;
  acceptedBg: string;
  rejected: string;
  rejectedBg: string;
  overlay: string;
  white: string;
  navyDark: string;
  navyMedium: string;
  isDark: boolean;
  fontRegular: string;
  fontMedium: string;
  fontSemiBold: string;
  fontBold: string;
  fontTitle: string;
  tabBarBg: string;
  inputBg: string;
  inputBorder: string;
  headerBg: string;
  shadow: string;
}

export const LightTheme: ThemeColors = {
  background: "#F8F9FC",
  surface: "#FFFFFF",
  surfaceSecondary: "#F1F3F9",
  surfaceElevated: "#E8EAF0",
  card: "#FFFFFF",
  text: "#111827",
  textSecondary: "#4B5563",
  textTertiary: "#9CA3AF",
  border: "#E5E7EB",
  borderLight: "#F3F4F6",
  primary: "#4F46E5",
  primaryDark: "#4338CA",
  primaryLight: "#6366F1",
  accent: "#7C3AED",
  error: "#EF4444",
  errorLight: "#FEE2E2",
  success: "#10B981",
  successLight: "#D1FAE5",
  warning: "#F59E0B",
  warningLight: "#FEF3C7",
  pending: "#F59E0B",
  pendingBg: "#FEF3C7",
  accepted: "#10B981",
  acceptedBg: "#D1FAE5",
  rejected: "#EF4444",
  rejectedBg: "#FEE2E2",
  overlay: "rgba(0,0,0,0.5)",
  white: "#FFFFFF",
  navyDark: "#111827",
  navyMedium: "#1F2937",
  isDark: false,
  fontRegular: "Inter_400Regular",
  fontMedium: "Inter_500Medium",
  fontSemiBold: "Inter_600SemiBold",
  fontBold: "Inter_700Bold",
  fontTitle: "Inter_700Bold",
  tabBarBg: "#FFFFFF",
  inputBg: "#FFFFFF",
  inputBorder: "#E5E7EB",
  headerBg: "#FFFFFF",
  shadow: "#000000",
};

export const DarkTheme: ThemeColors = {
  background: "#0F1117",
  surface: "#1A1D2B",
  surfaceSecondary: "#1F2235",
  surfaceElevated: "#262A3D",
  card: "#1A1D2B",
  text: "#F3F4F6",
  textSecondary: "#9CA3AF",
  textTertiary: "#6B7280",
  border: "#2D3148",
  borderLight: "#232740",
  primary: "#6366F1",
  primaryDark: "#4F46E5",
  primaryLight: "#818CF8",
  accent: "#A78BFA",
  error: "#F87171",
  errorLight: "rgba(239,68,68,0.18)",
  success: "#34D399",
  successLight: "rgba(16,185,129,0.15)",
  warning: "#FBBF24",
  warningLight: "rgba(245,158,11,0.15)",
  pending: "#FBBF24",
  pendingBg: "rgba(245,158,11,0.15)",
  accepted: "#34D399",
  acceptedBg: "rgba(16,185,129,0.15)",
  rejected: "#F87171",
  rejectedBg: "rgba(239,68,68,0.18)",
  overlay: "rgba(0,0,0,0.75)",
  white: "#FFFFFF",
  navyDark: "#F3F4F6",
  navyMedium: "#D1D5DB",
  isDark: true,
  fontRegular: "Inter_400Regular",
  fontMedium: "Inter_500Medium",
  fontSemiBold: "Inter_600SemiBold",
  fontBold: "Inter_700Bold",
  fontTitle: "Inter_700Bold",
  tabBarBg: "#151828",
  inputBg: "#1F2235",
  inputBorder: "#2D3148",
  headerBg: "#151828",
  shadow: "#000000",
};

export const Colors = LightTheme;
export default Colors;
